from pathlib import Path
p=Path('dist/game.js');s=p.read_text(encoding='utf-8')
s=s.replace("hover=null,tool='normal'", "hover=null,pendingAim=null,tool='normal'")
s=s.replace('function reset(){CORE=44;', 'function reset(){pendingAim=null;CORE=44;')
s=s.replace("phase!=='build'||CORE===null", "phase!=='build'||CORE===null||pendingAim!==null")
s=s.replace("function end(won){phase=", "function end(won){pendingAim=null;phase=")
s=s.replace("canvas.addEventListener('pointermove',e=>{hover=pointer(e)});", "function aimAt(p){if(!pendingAim)return;const dx=p.x-pendingAim.x,dy=p.y-pendingAim.y;if(Math.hypot(dx,dy)>.03)setAngle(Math.atan2(dy,dx)*180/Math.PI)}\nfunction confirmAim(p){aimAt(p);if(pendingAim.existing){pendingAim.existing.angle=angle;}else{towers.push({cell:pendingAim.cell,x:pendingAim.x,y:pendingAim.y,type:pendingAim.type,angle,cool:0});}pendingAim=null;message('방향 확정 완료. 포탑이 지정한 방향으로 발사합니다.');ui()}\ncanvas.addEventListener('pointermove',e=>{hover=pointer(e);aimAt(hover)});")
s=s.replace("if(x<0||x>=10||y<0||y>=10)return;const w=", "if(x<0||x>=10||y<0||y>=10)return;if(pendingAim){confirmAim(p);return}const w=")
s=s.replace("if(t){t.angle=angle;message('포탑의 발사 방향을 변경했습니다.');}", "if(t){pendingAim={...t,existing:t};setAngle(t.angle*180/Math.PI);message('커서로 방향을 잡고 클릭으로 확정하세요. Esc로 취소합니다.');}")
s=s.replace("towers.push({cell:id,...center(id),type:tool,angle,cool:0});message('포탑 설치 완료. 선택한 방향으로 자동 발사합니다.');", "pendingAim={cell:id,...center(id),type:tool,angle};message('위치 선택 완료. 커서로 방향을 잡고 다시 클릭하세요. Esc로 취소합니다.');")
s=s.replace("b.onclick=()=>{tool=b.dataset.tool;", "b.onclick=()=>{pendingAim=null;tool=b.dataset.tool;")
s=s.replace('angle=d*Math.PI/180;', 'angle=d*Math.PI/180;if(pendingAim)pendingAim.angle=angle;')
s=s.replace("window.addEventListener('keydown',e=>{", "window.addEventListener('keydown',e=>{if(e.key==='Escape'&&pendingAim){pendingAim=null;message('포탑 조준을 취소했습니다.');ui();return;}")
s=s.replace('function moveBullet(b,dt){let expired=false;', "function moveBullet(b,dt){let expired=false;if(b.type==='normal'){const speed=Math.hypot(b.vx,b.vy),leftRange=Math.max(0,6-(b.traveled??0));if(leftRange<=1e-9)return false;if(speed>0){dt=Math.min(dt,leftRange/speed);b.traveled=(b.traveled??0)+speed*dt;expired=b.traveled>=6-1e-9;}}")
s=s.replace('type:t.type,age:0,contacts:', 'type:t.type,age:0,traveled:0,contacts:')
s=s.replace('step=(.78+round*.04)*dt', 'step=(.78+round*.04)*1.2*dt')
s=s.replace("ctx.globalAlpha=1;if(hover&&phase", "ctx.globalAlpha=1;if(pendingAim){const a=pendingAim;ctx.save();ctx.translate(a.x*s,a.y*s);ctx.rotate(a.angle);ctx.strokeStyle=a.type==='bank'?'#ffc16b':'#6de6db';ctx.fillStyle=a.type==='bank'?'#66482d':'#245354';ctx.globalAlpha=.85;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,20,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(0,-5,28,10);ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(28,0);ctx.lineTo((a.type==='normal'?6:12)*s,0);ctx.stroke();ctx.restore();return;}if(hover&&phase")
p.write_text(s,encoding='utf-8')
p=Path('dist/index.html');s=p.read_text(encoding='utf-8').replace('3 피해 · 0.5초 간격', '3 피해 · 0.5초 간격 · 사거리 6칸')
s=s.replace('도구를 선택하고 맵에 배치하세요.', '포탑 위치 클릭 → 커서 조준 → 클릭 확정')
s=s.replace('0°는 오른쪽, 90°는 아래쪽입니다.<br>각도를 입력한 후 포탑을 배치하세요.<br>설치된 포탑을 클릭하면 방향이 바뀝니다.', '맵 클릭으로 위치 선택 → 커서로 조준 → 다시 클릭해 확정.<br>설치된 포탑도 클릭 후 재조준할 수 있습니다. Esc로 취소.<br>각도 입력으로 미세 조절할 수도 있습니다.')
s=s.replace('일반 탄환은 벽과 적에 닿으면 소멸합니다.', '일반 탄환은 6칸 이동하거나 벽·적에 닿으면 소멸합니다.')
p.write_text(s,encoding='utf-8')
html=s.replace('<link rel="stylesheet" href="style.css">','<style>'+Path('dist/style.css').read_text(encoding='utf-8')+'</style>').replace('<script src="game.js"></script>','<script>'+Path('dist/game.js').read_text(encoding='utf-8')+'</script>')
Path('outputs/nexus-defense.html').write_text(html,encoding='utf-8')
