const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const nodes=new Map(),node=()=>({textContent:'',innerHTML:'',hidden:true,disabled:false,dataset:{},listeners:{},classList:{toggle(){}},addEventListener(type,fn){this.listeners[type]=fn},getContext(){return {}},getBoundingClientRect(){return {left:0,top:0,width:800,height:800}}});
const sandbox={document:{getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelectorAll(){return []},addEventListener(){}},window:{addEventListener(){}},performance:{now:()=>0},requestAnimationFrame(){},HTMLButtonElement:class{},console,Math,Set,Map};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/game.js','utf8'),sandbox);
const run=s=>vm.runInContext(s,sandbox);
run('const terrainReset=reset;reset=function(){terrainReset();obstacles.clear();obstacleGroups=[];refreshSpawnCandidates();spawns=[];addSpawnPoint();dist=distances()};reset()');
assert.equal(run('CORE===44&&spawns.length===1&&spawnCandidates.length===59'),true);
assert.equal(run('spawns.every(i=>spawnCandidates.includes(i)&&dist[i]>=5)'),true);
assert.equal(run("tool='remove';canvas.listeners.pointerdown({clientX:360,clientY:360});CORE===44"),true);
assert.equal(run("tool='normal';canvas.listeners.pointerdown({clientX:360,clientY:360});towers.length===0&&CORE===44"),true);
assert.equal(run('setAngle(37.5);Math.abs(angle-37.5*Math.PI/180)<1e-10'),true);
assert.equal(run('setAngle(360);angle===0'),true);
assert.equal(run("reset();setAngle(123.4);tool='bank';canvas.listeners.pointerdown({clientX:120,clientY:120});canvas.listeners.pointerdown({clientX:120,clientY:120});start();spawnClock=Infinity;update(STEP);Math.abs(bullets[0].vx-6*Math.cos(123.4*Math.PI/180))<1e-10&&Math.abs(bullets[0].vy-6*Math.sin(123.4*Math.PI/180))<1e-10"),true);
run('reset()');
assert.equal(run("walls.set(edge(44,45),{x1:5,y1:4,x2:5,y2:5});dist=distances();dist[45]"),3);
assert.equal(run("[34,43,54].forEach(i=>walls.set(edge(44,i),{}));distances().filter(Number.isFinite).length"),1);
assert.equal(run("reset();walls.set(edge(0,1),{x1:1,y1:0,x2:1,y2:1});let b={x:.9,y:.5,vx:6,vy:0,type:'bank',contacts:new Set()};moveBullet(b,.04);b.vx"),-6);
assert.equal(run("moveBullet({x:.9,y:.5,vx:6,vy:0,type:'normal',contacts:new Set()},.04)"),true);
assert.equal(run("reset();enemies=[{id:1,x:1,y:1,hp:8},{id:2,x:1.5,y:1,hp:8}];moveBullet({x:.5,y:1,vx:6,vy:0,type:'bank',contacts:new Set()},.2);enemies.every(e=>e.hp===7)"),true);
assert.equal(run("enemies.forEach(e=>e.hp=8);moveBullet({x:.5,y:1,vx:6,vy:0,type:'normal',targetId:1,contacts:new Set()},.2);enemies[0].hp===5&&enemies[1].hp===8"),true);
assert.equal(run("reset();start();paused=true;update(1);remaining"),40);
assert.equal(run("reset();for(let r=1;r<=8;r++){start();spawnClock=Infinity;for(let i=0;i<(r>=5?7201:4801);i++)update(STEP)}phase"),'won');
assert.equal(run("reset();start();hp=1;enemies=[{id:1,cell:43,to:44,x:4.5,y:4.5,hp:8}];update(STEP);phase"),'lost');
assert.equal(run("hp"),0);
assert.equal(run("reset();let timed={x:2,y:2,vx:0,vy:0,type:'bank',age:0,contacts:new Set()};moveBullet(timed,3.99)"),true);
assert.equal(run("moveBullet(timed,.01)"),false);
assert.equal(run("reset();start();bullets=[{x:2,y:2,vx:0,vy:0,type:'bank',age:1,contacts:new Set()}];paused=true;update(3);bullets[0].age"),1);
assert.equal(run("reset();enemies=[{id:1,x:1,y:1,hp:1}];moveBullet({x:.5,y:1,vx:6,vy:0,type:'bank',age:0,contacts:new Set()},.1);roundKills===1&&kills===1"),true);
assert.equal(run("enemies=[];phase='active';remaining=STEP;spawnClock=Infinity;update(STEP);roundResults[0].kills===1&&roundResults[0].round===1&&round===2"),true);
assert.equal(run("start();roundKills===0&&kills===1"),true);
assert.equal(run("round=8;roundKills=4;remaining=STEP;spawnClock=Infinity;update(STEP);phase==='won'&&roundResults[1].round===8&&roundResults[1].kills===4"),true);
assert.equal(nodes.get('round-results').innerHTML.includes('4마리 처치'),true);
assert.equal(run('reset();roundResults.length===0&&roundKills===0&&kills===0'),true);
console.log('PASS: spawn distance, shortest detour, enclosure detection, bank reflection, normal wall passthrough, piercing, pause, eight rounds, defeat.');
console.log('PASS: four-second bank lifetime, paused lifetime, per-round kills, final-round report, reset.');
assert.equal(run("reset();tool='normal';canvas.listeners.pointerdown({clientX:120,clientY:120});towers.length===1&&towers[0].cell===11"),true);
assert.equal(run("start();phase==='active'"),true);
assert.equal(run("reset();tool='bank';canvas.listeners.pointerdown({clientX:120,clientY:120});canvas.listeners.pointermove({clientX:200,clientY:200});towers.length===0&&Math.abs(pendingAim.angle-Math.PI/4)<1e-10"),true);
assert.equal(run("canvas.listeners.pointerdown({clientX:200,clientY:200});towers.length===1&&Math.abs(towers[0].angle-Math.PI/4)<1e-10"),true);
assert.equal(run("reset();let ranged={x:1,y:1,vx:6,vy:0,type:'normal',contacts:new Set()};moveBullet(ranged,.8)"),true);
assert.equal(run("moveBullet(ranged,1/30)===false&&Math.abs(ranged.x-6)<1e-10"),true);
assert.equal(run("reset();enemies=[{id:1,x:6.3,y:1,hp:8}];moveBullet({x:1,y:1,vx:6,vy:0,type:'normal',contacts:new Set()},2);enemies[0].hp===8"),true);
assert.equal(run("reset();moveBullet({x:1,y:1,vx:6,vy:0,type:'bank',age:0,contacts:new Set()},1.1)"),true);
assert.equal(run("reset();start();spawnClock=Infinity;enemies=[{id:1,cell:0,to:1,x:.5,y:.5,hp:8}];update(.1);Math.abs(enemies[0].x-(.5+(.78+.04)*1.44*.1))<1e-10"),true);
console.log('PASS: single-click placement and fixed bank direction, five-cell range, bank range exemption, 1.44x original enemy speed.');

assert.equal(run('reset();[8,11,20,32,47,65,86,110].every((expected,i)=>{round=i+1;enemies=[];spawn();ui();return enemies[0].hp===expected&&enemies[0].max===expected&&$("enemy-hp").textContent===`적 HP ${expected}`})'),true);
console.log('PASS: all eight round HP values and displayed HP.');

assert.equal(run('reset();money===10&&shopOffers.length===0&&buyItem(0)===false'),true);
assert.equal(run("start();spawnClock=Infinity;remaining=STEP;update(STEP);round===2&&shopOffers.length===2&&new Set(shopOffers).size===2"),true);
assert.equal(run('money=100;shopOffers=[0,1];buyItem(0)&&!buyItem(0)&&money===85&&weaponStats().bankLife===5'),true);
assert.equal(run('buyItem(1)&&!buyItem(1)&&money===75&&weaponStats().bankDamage===2'),true);
assert.equal(nodes.get('shop-items').innerHTML.split('구매 완료').length-1,2);
assert.equal(run('start();buyItem(0)===false;spawnClock=Infinity;remaining=STEP;update(STEP);round===3&&shopPurchased.size===0&&weaponStats().bankLife===5'),true);
assert.equal(run('shopOffers=[0,1];buyItem(0)&&money===60&&weaponStats().bankLife===6'),true);
assert.equal(run('shopOffers=[2,3];buyItem(2)&&!buyItem(2)&&Math.abs(weaponStats().bankInterval-2.5)<1e-10&&buyItem(3)&&weaponStats().normalDamage===4'),true);
assert.equal(run('shopOffers=[4,5];buyItem(4)&&weaponStats().normalShots===2&&buyItem(5)&&weaponStats().normalCrit===.1&&money===15'),true);
assert.equal(run('rollShop();shopOffers=[0,1];money=9;!buyItem(1)&&money===9&&!shopPurchased.has(1)'),true);
assert.equal(run('money=100;start();!buyItem(1)&&money===100'),true);
assert.equal(run('paused=true;!buyItem(1)&&money===100'),true);
assert.equal(run("paused=false;bullets=[];upgrades.normalCrit=10;fireTower({x:2,y:2,angle:0,type:'normal',targetId:20});bullets.length===2&&bullets.every(b=>b.damage===8&&b.critical&&b.targetId===20)"),true);
assert.equal(run("enemies=[{id:20,x:2.4,y:2,hp:8}];bullets=bullets.filter(b=>moveBullet(b,.1));money===101&&kills===1"),true);
assert.equal(run("enemies=[];bullets=[];fireTower({x:2,y:2,angle:0,type:'bank'});bullets[0].life===6&&bullets[0].damage===2"),true);
assert.equal(run("let upgradedBullet=bullets[0];upgradedBullet.vx=0;upgradedBullet.vy=0;moveBullet(upgradedBullet,5.9)&&!moveBullet(upgradedBullet,.1)"),true);
assert.equal(run("bullets=[];enemies=[];towers=[{x:2,y:2,angle:0,type:'bank',cool:0}];spawnClock=Infinity;update(STEP);Math.abs(towers[0].cool-(2.5-STEP))<1e-9"),true);
assert.equal(run('reset();money===10&&weaponStats().bankLife===4&&weaponStats().normalShots===1&&shopOffers.length===0&&shopPurchased.size===0'),true);
assert.equal(run('Array.from({length:8},(_,i)=>{reset();round=i+1;start();update(STEP);return Math.abs(spawnClock-([1,.8,.4,.3,.2,.18,.16,.14][i]-STEP))<1e-10}).every(Boolean)'),true);
console.log('PASS: one purchase per item per round, both offers purchasable, re-purchase next round, funds, all upgrades, reset and increasing per-round spawn rates.');

const waveCounts=run('Array.from({length:8},(_,i)=>{reset();round=i+1;start();for(let n=0;n<(i>=4?7200:4800);n++){enemies=[];update(STEP)}return nextId})');
assert.ok(waveCounts.every((count,i)=>Math.abs(count-[40,50,100,134,300,334,375,429][i])<=1));
assert.ok(waveCounts.every((count,i)=>i===0||count>waveCounts[i-1]));
assert.equal(run("reset();start();spawnClock=Infinity;for(let n=0;n<4799;n++)update(STEP);phase==='active'"),true);
assert.equal(run("update(STEP);phase==='build'&&round===2&&remaining===40"),true);
assert.equal(run("reset();round=4;phase='active';remaining=STEP;spawnClock=Infinity;update(STEP);round===5&&phase==='build'&&remaining===60;start();remaining===60"),true);
console.log('PASS: 40-second rounds 1-4, 60-second rounds 5-8 and increasing enemy totals:',Array.from(waveCounts));

assert.equal(run('Array.from({length:30},()=>{terrainReset();return obstacleGroups.length>=2&&obstacleGroups.length<=4&&obstacleGroups.every(g=>g.length>=2&&g.length<=5)&&!obstacles.has(CORE)&&dist.every((d,i)=>obstacles.has(i)||Number.isFinite(d))&&spawns.every(i=>!obstacles.has(i))}).every(Boolean)'),true);
assert.equal(run("let blocked=[...obstacles][0];tool='normal';canvas.listeners.pointerdown({clientX:(blocked%10+.5)*80,clientY:(Math.floor(blocked/10)+.5)*80});towers.length===0&&CORE===44"),true);
assert.equal(run("let terrainSignature=[...obstacles].join(',');start();remaining=STEP;spawnClock=Infinity;update(STEP);[...obstacles].join(',')===terrainSignature"),true);
assert.equal(run("terrainReset();[...obstacles].join(',')!==terrainSignature"),true);
assert.equal(run("reset();obstacles=new Set([45]);refreshSpawnCandidates();spawns=[];addSpawnPoint();dist=distances();dist[45]===Infinity&&dist[46]===4&&!spawnCandidates.includes(45)"),true);
console.log('PASS: random terrain size, connected map, placement and spawn exclusion, round persistence, new-game changes and detour.');
assert.equal(run("reset();enemies=[{id:91,x:1.3,y:1.24,hp:8}];moveBullet({x:1,y:1,vx:6,vy:0,type:'bank',contacts:new Set()},.1);enemies[0].hp===7"),true);
assert.equal(run("enemies[0].hp=8;moveBullet({x:1,y:1,vx:6,vy:0,type:'normal',targetId:91,contacts:new Set()},.1);enemies[0].hp===5"),true);
assert.equal(run("enemies[0].hp=8;enemies[0].y=1.26;moveBullet({x:1,y:1,vx:6,vy:0,type:'bank',contacts:new Set()},.1);enemies[0].hp===8"),true);
console.log('PASS: bank hit radius increased 20%, outside boundary excluded, normal hit radius also increased 20%.');
assert.equal(run('reset();towerCapacity()===4'),true);
assert.equal(run("tool='normal';for(let i=0;i<4;i++){canvas.listeners.pointerdown({clientX:(i+.5)*80,clientY:40});canvas.listeners.pointerdown({clientX:(i+.5)*80,clientY:40})}canvas.listeners.pointerdown({clientX:360,clientY:40});towers.length===4"),true);
assert.equal(run('money=500;!buyItem(6)&&money===500'),true);
assert.equal(run('start();spawnClock=Infinity;remaining=STEP;update(STEP);round===2&&towerCapacity()===4&&shopOffers.length===2&&!shopOffers.includes(6)'),true);
assert.equal(run('buyItem(6)&&buyItem(6)&&towerCapacity()===6&&money===440&&!shopPurchased.has(6)'),true);
assert.equal(run("canvas.listeners.pointerdown({clientX:360,clientY:40});canvas.listeners.pointerdown({clientX:360,clientY:40});towers.length===5"),true);
assert.equal(run('money=29;!buyItem(6)&&towerCapacity()===6&&money===29'),true);
assert.equal(run('money=100;start();buyItem(6)&&money===70&&towerCapacity()===7;spawnClock=Infinity;remaining=STEP;update(STEP);towerCapacity()===7&&round===3'),true);
assert.equal(run('buyItem(6)&&towerCapacity()===8&&money===40'),true);
assert.equal(run('reset();towerCapacity()===4'),true);
console.log('PASS: fixed four-tower cap, blocked fifth placement, unlimited 30-coin capacity purchases, funds, round persistence and reset.');
assert.equal(run("reset();let autoTower={x:1.5,y:1.5,type:'normal',angle:0,cool:0};enemies=[{id:1,x:2,y:1.5,hp:8},{id:2,x:4,y:3,hp:8},{id:3,x:8,y:8,hp:8}];selectTarget(autoTower).id===2"),true);
assert.equal(run("enemies[1].hp=0;selectTarget(autoTower).id===1"),true);
assert.equal(run("enemies=[{id:4,x:9,y:9,hp:8}];selectTarget(autoTower)===null"),true);
assert.equal(run("reset();start();spawnClock=Infinity;towers=[{x:1.5,y:1.5,type:'normal',angle:0,cool:0}];update(STEP);bullets.length===0"),true);
assert.equal(run("enemies=[{id:5,cell:32,to:null,x:2.5,y:3.5,hp:8}];update(STEP);bullets.length===1&&Math.abs(towers[0].angle-Math.atan2(2,1))<1e-10"),true);
assert.equal(run("reset();walls.set(edge(0,1),{x1:1,y1:0,x2:1,y2:1});enemies=[{id:1,x:1.3,y:.5,hp:8}];moveBullet({x:.7,y:.5,vx:6,vy:0,type:'normal',targetId:1,contacts:new Set()},.15);enemies[0].hp===5"),true);
assert.equal(run("reset();round=2;start();money=150;shopOffers=[0,1];buyItem(6)&&buyItem(6)&&money===90&&towerCapacity()===6&&!buyItem(0)"),true);
assert.equal(run("paused=true;buyItem(6)&&money===60&&towerCapacity()===7"),true);
assert.equal(run("end(true);money=100;!buyItem(6)&&money===100"),true);
console.log('PASS: nearest-to-core targeting within range, no-target hold fire, wall-through hits, repeated battle capacity purchase and other-item lock.');
assert.equal(run("reset();start();spawnClock=.8;setDifficulty('count',2);Math.abs(spawnClock-.4)<1e-10"),true);
assert.equal(run("setDifficulty('speed',2);spawnClock=Infinity;enemies=[{id:1,cell:0,to:1,x:.5,y:.5,hp:8}];update(.1);Math.abs(enemies[0].x-(.5+(.78+.04)*1.44*2*.1))<1e-10"),true);
assert.equal(run("reset();difficulty.count===2&&difficulty.speed===2"),true);
assert.equal(run("$('options-dialog').showModal=function(){this.open=true};start();openOptions();paused&&optionsResume"),true);
assert.equal(run("$('options-dialog').open=false;closeOptions();!paused"),true);
assert.equal(run("paused=true;openOptions();$('options-dialog').open=false;closeOptions();paused"),true);
assert.equal(run("setDifficulty('count',1);setDifficulty('speed',1);difficulty.count===1&&difficulty.speed===1"),true);
assert.ok(!fs.readFileSync('dist/index.html','utf8').includes('id="angle-range"'));
console.log('PASS: live difficulty scaling, settings retention, option pause/resume and removed direction slider.');

assert.ok(!fs.readFileSync('dist/index.html','utf8').includes('id="angle-number"'));
console.log('PASS: bank cursor aim restored and direction panel removed.');

assert.equal(run("reset();let lockTower={x:2,y:2,type:'normal',cool:0};enemies=[{id:101,x:3,y:3,hp:8},{id:102,x:1,y:2,hp:8}];selectTarget(lockTower).id===101"),true);
assert.equal(run("enemies[1].x=4.5;enemies[1].y=4.5;selectTarget(lockTower).id===101"),true);
assert.equal(run("enemies[0].x=9;enemies[0].y=9;selectTarget(lockTower).id===102&&lockTower.targetId===102"),true);
assert.equal(run("enemies[0].x=3;enemies[0].y=3;selectTarget(lockTower).id===102"),true);
assert.equal(run("enemies[1].hp=0;selectTarget(lockTower).id===101&&lockTower.targetId===101"),true);
assert.equal(run("enemies=[];selectTarget(lockTower)===null&&lockTower.targetId===null"),true);
assert.equal(run("reset();start();spawnClock=Infinity;towers=[{x:2,y:2,type:'normal',cool:0}];enemies=[{id:10,cell:33,to:null,x:3.5,y:3.5,hp:8}];update(STEP);Math.abs(towers[0].cool-(.5/1.1-STEP))<1e-10"),true);
assert.equal(run("reset();enemies=[{id:1,x:1.3,y:1.26,hp:8}];moveBullet({x:1,y:1,vx:6,vy:0,type:'normal',targetId:1,contacts:new Set()},.1);enemies[0].hp===8"),true);
console.log('PASS: 10% normal fire rate increase, target lock until death/removal, range hold and enlarged hit boundary.');
assert.equal(run("reset();enemies=[{id:201,x:1.5,y:1,hp:8},{id:202,x:2,y:1,hp:8}];moveBullet({x:1,y:1,vx:6,vy:0,type:'normal',targetId:202,contacts:new Set()},.2);enemies[0].hp===8&&enemies[1].hp===5"),true);
assert.equal(run("reset();let aimed={x:1,y:1,type:'normal',angle:0,targetId:301};enemies=[{id:301,x:2,y:1,hp:8}];bullets=[];fireTower(aimed);bullets[0].targetId===301"),true);
assert.equal(run("let retarget={x:2,y:2,type:'normal',targetId:401};enemies=[{id:401,x:8,y:8,hp:8},{id:402,x:3,y:3,hp:8}];selectTarget(retarget).id===402&&retarget.targetId===402"),true);
console.log('PASS: normal bullets damage only their assigned target and towers immediately retarget out-of-range enemies.');

assert.equal(run("reset();Array.from({length:30},()=>{enemies=[];spawn();return spawns.includes(enemies[0].cell)}).every(Boolean)"),true);
assert.equal(run("reset();let spawnHistory=[spawns[0]];Array.from({length:7},()=>{phase='active';remaining=STEP;spawnClock=Infinity;update(STEP);return spawns.length===round&&new Set(spawns).size===spawns.length&&spawnHistory.every(i=>spawns.includes(i))&&(spawnHistory=[...spawns])}).every(Boolean)&&round===8"),true);
assert.equal(run("spawns.every(i=>spawnCandidates.includes(i)&&Math.abs(i%10-CORE%10)+Math.abs(Math.floor(i/10)-Math.floor(CORE/10))>=5)"),true);
assert.ok(!fs.readFileSync('dist/index.html','utf8').includes('id="core-tool"'));
console.log('PASS: fixed central core, one persistent spawn point per round, eligible spawn distance and removed core controls.');
assert.equal(run("reset();start();spawnClock=Infinity;remaining=STEP;update(STEP);round===2&&phase==='build'"),true);
assert.equal(run("money=200;buyItem(7)&&buyItem(7)&&buyItem(8)&&money===125&&radarStock.speedRadar===2&&radarStock.attackRadar===1&&!shopPurchased.has(7)&&!shopPurchased.has(8)"),true);
assert.equal(run("shopOffers=[0,1];shopSignature='';shopUI();$('shop-items').innerHTML.includes('공속 레이더')&&$('shop-items').innerHTML.includes('공격 레이더')&&$('shop-items').innerHTML.includes('30원')"),true);
assert.equal(run("tool='speedRadar';obstacles.clear();towers=[];canvas.listeners.pointerdown({clientX:40,clientY:40});towers.length===1&&towers[0].type==='speedRadar'&&radarStock.speedRadar===1"),true);
assert.equal(run("tool='attackRadar';canvas.listeners.pointerdown({clientX:120,clientY:40});towers.length===2&&towers[1].type==='attackRadar'&&radarStock.attackRadar===0"),true);
assert.equal(run("tool='remove';canvas.listeners.pointerdown({clientX:40,clientY:40});towers.length===1&&radarStock.speedRadar===2"),true);
assert.equal(run("towers=[{x:.5,y:.5,type:'normal'},{x:3.5,y:.5,type:'speedRadar'},{x:.5,y:3.5,type:'attackRadar'},{x:3.6,y:.5,type:'attackRadar'}];let bonuses=radarBonuses(towers[0]);Math.abs(bonuses.speed-1.3)<1e-10&&bonuses.damage===2"),true);
assert.equal(run("towers.push({x:.5,y:2.5,type:'speedRadar'});Math.abs(radarBonuses(towers[0]).speed-1.69)<1e-10"),true);
assert.equal(run("bullets=[];upgrades.normalCrit=0;let boosted=towers[0];boosted.angle=0;boosted.targetId=77;fireTower(boosted);bullets[0].damage===5&&bullets[0].targetId===77"),true);
assert.equal(run("bullets=[];fireTower({x:.5,y:.5,type:'bank',angle:0});bullets[0].damage===3"),true);
assert.equal(run("phase='active';paused=false;spawnClock=Infinity;enemies=[{id:77,cell:1,to:null,x:1.5,y:.5,hp:20}];towers=[boosted,{x:3.5,y:.5,type:'speedRadar'}];boosted.cool=0;update(STEP);Math.abs(boosted.cool-(NORMAL_INTERVAL/1.3-STEP))<1e-10&&bullets.length===2"),true);
assert.equal(run("money=100;buyItem(7)&&buyItem(8)&&buyItem(6)&&money===20"),true);
assert.equal(run("reset();round=2;phase='build';money=100;radarStock.speedRadar=1;obstacles.clear();towers=[{cell:0,x:.5,y:.5,type:'normal'},{cell:1,x:1.5,y:.5,type:'normal'},{cell:2,x:2.5,y:.5,type:'normal'},{cell:3,x:3.5,y:.5,type:'normal'}];tool='speedRadar';canvas.listeners.pointerdown({clientX:360,clientY:40});towers.length===5&&placedTowerCount()===4&&towerCapacity()===4&&radarStock.speedRadar===0"),true);
assert.equal(run("reset();radarStock.speedRadar===0&&radarStock.attackRadar===0&&towerCapacity()===4"),true);
console.log('PASS: repeatable 25-coin radar shop, battle purchase, capacity-free placement, three-cell range, stacking, attack and speed boosts.');
