const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const nodes=new Map(),node=()=>({textContent:'',innerHTML:'',hidden:true,disabled:false,dataset:{},listeners:{},classList:{toggle(){}},addEventListener(type,fn){this.listeners[type]=fn},getContext(){return {}},getBoundingClientRect(){return {left:0,top:0,width:800,height:800}}});
const sandbox={document:{getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelectorAll(){return []},addEventListener(){}},window:{addEventListener(){}},performance:{now:()=>0},requestAnimationFrame(){},HTMLButtonElement:class{},console,Math,Set,Map};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/game.js','utf8'),sandbox);
const run=s=>vm.runInContext(s,sandbox);
run('const terrainReset=reset;reset=function(){terrainReset();obstacles.clear();obstacleGroups=[];refreshSpawns();dist=distances()};reset()');
assert.equal(run('spawns.length'),59);assert.equal(run('spawns.every(i=>dist[i]>=5)&&spawns.some(i=>dist[i]>5)'),true);
assert.equal(run('Array.from({length:100},(_,id)=>{placeCore(id);return dist[id]===0&&spawns.length>0&&Array.from({length:100},(_,i)=>spawns.includes(i)===(Math.abs(i%10-id%10)+Math.abs(Math.floor(i/10)-Math.floor(id/10))>=5)).every(Boolean)}).every(Boolean)'),true);
assert.equal(run('reset();hp=6;placeCore(0);hp===6&&CORE===0&&spawns.length===85&&dist[99]===18'),true);
assert.equal(run('start();placeCore(99)===false&&CORE===0'),true);
assert.equal(run('paused=true;placeCore(99)===false&&CORE===0'),true);
assert.equal(run("tool='remove';canvas.listeners.pointerdown({clientX:40,clientY:40});CORE===0"),true);
assert.equal(run("paused=false;remaining=STEP;spawnClock=Infinity;update(STEP);phase==='build'&&placeCore(99)&&CORE===99&&hp===6"),true);
assert.equal(run("tool='remove';canvas.listeners.pointerdown({clientX:760,clientY:760});start();CORE===null&&phase==='build'"),true);
assert.equal(run("tool='core';canvas.listeners.pointerdown({clientX:120,clientY:120});CORE===11"),true);
assert.equal(run('towers.push({cell:22});placeCore(22)===false&&CORE===11'),true);
assert.equal(run('setAngle(37.5);Math.abs(angle-37.5*Math.PI/180)<1e-10'),true);
assert.equal(run('setAngle(360);angle===0'),true);
assert.equal(run("reset();setAngle(123.4);tool='normal';canvas.listeners.pointerdown({clientX:120,clientY:120});canvas.listeners.pointerdown({clientX:120,clientY:120});start();spawnClock=Infinity;update(STEP);Math.abs(bullets[0].vx-6*Math.cos(123.4*Math.PI/180))<1e-10&&Math.abs(bullets[0].vy-6*Math.sin(123.4*Math.PI/180))<1e-10"),true);
run('reset()');
assert.equal(run("walls.set(edge(44,45),{x1:5,y1:4,x2:5,y2:5});dist=distances();dist[45]"),3);
assert.equal(run("[34,43,54].forEach(i=>walls.set(edge(44,i),{}));distances().filter(Number.isFinite).length"),1);
assert.equal(run("reset();walls.set(edge(0,1),{x1:1,y1:0,x2:1,y2:1});let b={x:.9,y:.5,vx:6,vy:0,type:'bank',contacts:new Set()};moveBullet(b,.04);b.vx"),-6);
assert.equal(run("moveBullet({x:.9,y:.5,vx:6,vy:0,type:'normal',contacts:new Set()},.04)"),false);
assert.equal(run("reset();enemies=[{id:1,x:1,y:1,hp:8},{id:2,x:1.5,y:1,hp:8}];moveBullet({x:.5,y:1,vx:6,vy:0,type:'bank',contacts:new Set()},.2);enemies.every(e=>e.hp===7)"),true);
assert.equal(run("enemies.forEach(e=>e.hp=8);moveBullet({x:.5,y:1,vx:6,vy:0,type:'normal',contacts:new Set()},.2);enemies[0].hp===5&&enemies[1].hp===8"),true);
assert.equal(run("reset();start();paused=true;update(1);remaining"),40);
assert.equal(run("reset();for(let r=1;r<=5;r++){start();spawnClock=Infinity;for(let i=0;i<4801;i++)update(STEP)}phase"),'won');
assert.equal(run("reset();start();hp=1;enemies=[{id:1,cell:43,to:44,x:4.5,y:4.5,hp:8}];update(STEP);phase"),'lost');
assert.equal(run("hp"),0);
assert.equal(run("reset();let timed={x:2,y:2,vx:0,vy:0,type:'bank',age:0,contacts:new Set()};moveBullet(timed,3.99)"),true);
assert.equal(run("moveBullet(timed,.01)"),false);
assert.equal(run("reset();start();bullets=[{x:2,y:2,vx:0,vy:0,type:'bank',age:1,contacts:new Set()}];paused=true;update(3);bullets[0].age"),1);
assert.equal(run("reset();enemies=[{id:1,x:1,y:1,hp:1}];moveBullet({x:.5,y:1,vx:6,vy:0,type:'bank',age:0,contacts:new Set()},.1);roundKills===1&&kills===1"),true);
assert.equal(run("enemies=[];phase='active';remaining=STEP;spawnClock=Infinity;update(STEP);roundResults[0].kills===1&&roundResults[0].round===1&&round===2"),true);
assert.equal(run("start();roundKills===0&&kills===1"),true);
assert.equal(run("round=5;roundKills=4;remaining=STEP;spawnClock=Infinity;update(STEP);phase==='won'&&roundResults[1].round===5&&roundResults[1].kills===4"),true);
assert.equal(nodes.get('round-results').innerHTML.includes('4마리 처치'),true);
assert.equal(run('reset();roundResults.length===0&&roundKills===0&&kills===0'),true);
console.log('PASS: spawn distance, shortest detour, enclosure detection, bank reflection, normal absorption, piercing, pause, five rounds, defeat.');
console.log('PASS: four-second bank lifetime, paused lifetime, per-round kills, final-round report, reset.');
assert.equal(run("reset();tool='normal';canvas.listeners.pointerdown({clientX:120,clientY:120});towers.length===0&&pendingAim.cell===11"),true);
assert.equal(run("start();phase==='build'"),true);
assert.equal(run("canvas.listeners.pointermove({clientX:200,clientY:280});Math.abs(pendingAim.angle-Math.atan2(2,1))<1e-10"),true);
assert.equal(run("canvas.listeners.pointerdown({clientX:200,clientY:280});pendingAim===null&&towers.length===1&&towers[0].cell===11&&Math.abs(towers[0].angle-Math.atan2(2,1))<1e-10"),true);
assert.equal(run("canvas.listeners.pointerdown({clientX:120,clientY:120});canvas.listeners.pointermove({clientX:40,clientY:120});Math.abs(towers[0].angle-Math.atan2(2,1))<1e-10"),true);
assert.equal(run("canvas.listeners.pointerdown({clientX:40,clientY:120});towers.length===1&&Math.abs(towers[0].angle-Math.PI)<1e-10"),true);
assert.equal(run("reset();let ranged={x:1,y:1,vx:6,vy:0,type:'normal',contacts:new Set()};moveBullet(ranged,.8)"),true);
assert.equal(run("moveBullet(ranged,1/30)===false&&Math.abs(ranged.x-6)<1e-10"),true);
assert.equal(run("reset();enemies=[{id:1,x:6.3,y:1,hp:8}];moveBullet({x:1,y:1,vx:6,vy:0,type:'normal',contacts:new Set()},2);enemies[0].hp===8"),true);
assert.equal(run("reset();moveBullet({x:1,y:1,vx:6,vy:0,type:'bank',age:0,contacts:new Set()},1.1)"),true);
assert.equal(run("reset();start();spawnClock=Infinity;enemies=[{id:1,cell:0,to:1,x:.5,y:.5,hp:8}];update(.1);Math.abs(enemies[0].x-(.5+(.78+.04)*1.44*.1))<1e-10"),true);
console.log('PASS: two-click placement and re-aim, five-cell range, bank range exemption, 1.44x original enemy speed.');

assert.equal(run('reset();[8,11,20,32,47].every((expected,i)=>{round=i+1;enemies=[];spawn();ui();return enemies[0].hp===expected&&enemies[0].max===expected&&$("enemy-hp").textContent===`적 HP ${expected}`})'),true);
console.log('PASS: all five round HP values and displayed HP.');

assert.equal(run('reset();money===10&&shopOffers.length===0&&buyItem(0)===false'),true);
assert.equal(run("start();spawnClock=Infinity;remaining=STEP;update(STEP);round===2&&shopOffers.length===2&&new Set(shopOffers).size===2"),true);
assert.equal(run('money=100;shopOffers=[0,1];buyItem(0)&&!buyItem(0)&&money===85&&weaponStats().bankLife===5'),true);
assert.equal(run('buyItem(1)&&!buyItem(1)&&money===75&&weaponStats().bankDamage===2'),true);
assert.equal(nodes.get('shop-items').innerHTML.split('구매 완료').length-1,2);
assert.equal(run('start();buyItem(0)===false;spawnClock=Infinity;remaining=STEP;update(STEP);round===3&&shopPurchased.size===0&&weaponStats().bankLife===5'),true);
assert.equal(run('shopOffers=[0,1];buyItem(0)&&money===60&&weaponStats().bankLife===6'),true);
assert.equal(run('shopOffers=[2,3];buyItem(2)&&!buyItem(2)&&Math.abs(weaponStats().bankInterval-2.5)<1e-10&&buyItem(3)&&weaponStats().normalDamage===4'),true);
assert.equal(run('shopOffers=[4,5];buyItem(4)&&weaponStats().normalShots===2&&buyItem(5)&&weaponStats().normalCrit===.1&&money===15'),true);
assert.equal(run('rollShop();shopOffers=[0,1];money=9;!buyItem(1)&&money===9&&!shopPurchased.has(1)'),true);
assert.equal(run('money=100;start();!buyItem(1)&&money===100'),true);
assert.equal(run('paused=true;!buyItem(1)&&money===100'),true);
assert.equal(run("paused=false;bullets=[];upgrades.normalCrit=10;fireTower({x:2,y:2,angle:0,type:'normal'});bullets.length===2&&bullets.every(b=>b.damage===8&&b.critical)"),true);
assert.equal(run("enemies=[{id:20,x:2.4,y:2,hp:8}];bullets=bullets.filter(b=>moveBullet(b,.1));money===101&&kills===1"),true);
assert.equal(run("enemies=[];bullets=[];fireTower({x:2,y:2,angle:0,type:'bank'});bullets[0].life===6&&bullets[0].damage===2"),true);
assert.equal(run("let upgradedBullet=bullets[0];upgradedBullet.vx=0;upgradedBullet.vy=0;moveBullet(upgradedBullet,5.9)&&!moveBullet(upgradedBullet,.1)"),true);
assert.equal(run("bullets=[];enemies=[];towers=[{x:2,y:2,angle:0,type:'bank',cool:0}];spawnClock=Infinity;update(STEP);Math.abs(towers[0].cool-(2.5-STEP))<1e-9"),true);
assert.equal(run('reset();money===10&&weaponStats().bankLife===4&&weaponStats().normalShots===1&&shopOffers.length===0&&shopPurchased.size===0'),true);
assert.equal(run('Array.from({length:5},(_,i)=>{reset();round=i+1;start();update(STEP);return Math.abs(spawnClock-([1,.8,.4,.3,.2][i]-STEP))<1e-10}).every(Boolean)'),true);
console.log('PASS: one purchase per item per round, both offers purchasable, re-purchase next round, funds, all upgrades, reset and increasing per-round spawn rates.');

const waveCounts=run('Array.from({length:5},(_,i)=>{reset();round=i+1;start();for(let n=0;n<4800;n++){enemies=[];update(STEP)}return nextId})');
assert.ok(waveCounts.every((count,i)=>Math.abs(count-[40,50,100,134,200][i])<=1));
assert.ok(waveCounts.every((count,i)=>i===0||count>waveCounts[i-1]));
assert.equal(run("reset();start();spawnClock=Infinity;for(let n=0;n<4799;n++)update(STEP);phase==='active'"),true);
assert.equal(run("update(STEP);phase==='build'&&round===2&&remaining===40"),true);
console.log('PASS: 40-second duration and increasing enemy totals:',Array.from(waveCounts));

assert.equal(run('Array.from({length:30},()=>{terrainReset();return obstacleGroups.length>=2&&obstacleGroups.length<=4&&obstacleGroups.every(g=>g.length>=2&&g.length<=5)&&!obstacles.has(CORE)&&dist.every((d,i)=>obstacles.has(i)||Number.isFinite(d))&&spawns.every(i=>!obstacles.has(i))}).every(Boolean)'),true);
assert.equal(run("let blocked=[...obstacles][0];tool='normal';canvas.listeners.pointerdown({clientX:(blocked%10+.5)*80,clientY:(Math.floor(blocked/10)+.5)*80});towers.length===0&&pendingAim===null&&!placeCore(blocked)"),true);
assert.equal(run("let terrainSignature=[...obstacles].join(',');start();remaining=STEP;spawnClock=Infinity;update(STEP);[...obstacles].join(',')===terrainSignature"),true);
assert.equal(run("terrainReset();[...obstacles].join(',')!==terrainSignature"),true);
assert.equal(run("reset();obstacles=new Set([45]);refreshSpawns();dist=distances();dist[45]===Infinity&&dist[46]===4&&!spawns.includes(45)"),true);
console.log('PASS: random terrain size, connected map, placement and spawn exclusion, round persistence, new-game changes and detour.');
