from pathlib import Path
p=Path('dist/game.js');s=p.read_text(encoding='utf-8')
s=s.replace('const N=10, CORE=44, STEP=', 'let CORE=44;\nconst N=10, STEP=')
s=s.replace("const spawns=Array.from({length:100},(_,i)=>i).filter(i=>Math.abs(i%10-4)+Math.abs(Math.floor(i/10)-4)===5);", "let spawns=[];\nfunction refreshSpawns(){spawns=CORE===null?[]:Array.from({length:100},(_,i)=>i).filter(i=>Math.abs(i%10-CORE%10)+Math.abs(Math.floor(i/10)-Math.floor(CORE/10))>=5)}\nfunction placeCore(id){if(phase!=='build'){message('라운드 진행 중에는 넥서스를 옮기거나 제거할 수 없습니다.');return false}if(towers.some(t=>t.cell===id)){message('포탑이 없는 칸에 넥서스를 설치하세요.');return false}CORE=id;refreshSpawns();dist=distances();message('넥서스 위치를 변경했습니다. 내구도는 유지되며 생성 가능 칸이 갱신됩니다.');return true}")
s=s.replace('q=[CORE];d[CORE]=0;', 'q=[CORE??44];d[CORE??44]=0;')
s=s.replace('function reset(){walls=', 'function reset(){CORE=44;refreshSpawns();walls=')
s=s.replace("$('start').disabled=phase!=='build';", "$('start').disabled=phase!=='build'||CORE===null;$('core-tool').disabled=phase!=='build';")
s=s.replace("function start(){if(phase!=='build')return;", "function start(){if(phase!=='build'||CORE===null)return;")
s=s.replace("if(tool==='wall'){", "if(tool==='core'){placeCore(id);}else if(tool==='wall'){")
s=s.replace("}else{const n=towers.length;towers=towers.filter", "}else if(id===CORE){if(phase!=='build'){message('라운드 진행 중에는 넥서스를 제거할 수 없습니다.');return}CORE=null;refreshSpawns();dist=distances();message('넥서스를 제거했습니다. 넥서스를 다시 설치해야 라운드를 시작할 수 있습니다.');}else{const n=towers.length;towers=towers.filter")
s=s.replace("function setAngle(i){angle=i*Math.PI/4;$('angle-label').textContent=`${i*45}° ${arrows[i]}`;document.querySelectorAll('[data-angle]').forEach(b=>b.classList.toggle('active',+b.dataset.angle===i))}", "function setAngle(degrees){if(!Number.isFinite(degrees))return;const d=((degrees%360)+360)%360;angle=d*Math.PI/180;$('angle-label').textContent=`${Number(d.toFixed(2))}°`;$('angle-range').value=d;$('angle-number').value=Number(d.toFixed(2));document.querySelectorAll('[data-angle]').forEach(b=>b.classList.toggle('active',+b.dataset.angle*45===d))}")
s=s.replace('setAngle(+b.dataset.angle));setAngle(0);', "setAngle(+b.dataset.angle*45));$('angle-range').addEventListener('input',e=>setAngle(Number(e.target.value)));$('angle-number').addEventListener('input',e=>{if(e.target.value!=='')setAngle(Number(e.target.value))});setAngle(0);")
s=s.replace("window.addEventListener('keydown',e=>{", "window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;")
s=s.replace("if('1234'.includes(e.key))", "if(/^[1-5]$/.test(e.key))")
s=s.replace('const c=center(CORE),pulse=', 'if(CORE!==null){const c=center(CORE),pulse=')
s=s.replace('ctx.fillRect(-10,-10,20,20);ctx.restore();for(const t', 'ctx.fillRect(-10,-10,20,20);ctx.restore();}for(const t')
p.write_text(s,encoding='utf-8')
p=Path('dist/index.html');s=p.read_text(encoding='utf-8')
s=s.replace('중앙 넥서스를 60초 동안 지키세요','넥서스를 60초 동안 지키세요')
s=s.replace('<kbd>4</kbd></button></div>', '<kbd>4</kbd></button><button id="core-tool" class="tool" data-tool="core"><span class="icon">◇</span><span><b>넥서스 설치 / 이동</b><small>1개만 설치 · 라운드 준비 중 변경</small></span><kbd>5</kbd></button></div>')
s=s.replace('<div id="directions" class="directions"></div>', '<div class="angle-controls"><input id="angle-range" type="range" min="0" max="359.9" step="0.1" value="0" aria-label="발사 각도 조절"><label><input id="angle-number" type="number" min="0" max="360" step="any" value="0" aria-label="발사 각도 직접 입력">°</label></div><div id="directions" class="directions"></div>')
s=s.replace('방향 선택 후 포탑을 배치하세요.', '0°는 오른쪽, 90°는 아래쪽입니다.<br>각도를 입력한 후 포탑을 배치하세요.')
s=s.replace('모든 경로를 막는 벽은 설치할 수 없습니다.', '모든 경로를 막는 벽은 설치할 수 없습니다. 적은 넥서스에서 상하좌우 기준 5칸 이상 떨어진 칸에 생성됩니다. 넥서스는 준비 중에만 설치·이동·제거할 수 있습니다.')
p.write_text(s,encoding='utf-8')
p=Path('dist/style.css');s=p.read_text(encoding='utf-8')
s+='\n.angle-controls{display:flex;align-items:center;gap:12px;margin-bottom:12px}.angle-controls>input{flex:1;min-width:0;accent-color:var(--cyan)}.angle-controls label{display:flex;align-items:center;gap:5px;color:var(--cyan)}#angle-number{width:82px;background:var(--panel);border:1px solid var(--border);border-radius:5px;padding:8px;color:#eef3f9;font:14px "IBM Plex Mono",monospace}#core-tool{grid-column:1/-1}input:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}\n'
p.write_text(s,encoding='utf-8')
def bundle():
    html=Path('dist/index.html').read_text(encoding='utf-8').replace('<link rel="stylesheet" href="style.css">','<style>'+Path('dist/style.css').read_text(encoding='utf-8')+'</style>').replace('<script src="game.js"></script>','<script>'+Path('dist/game.js').read_text(encoding='utf-8')+'</script>')
    Path('outputs/nexus-defense.html').write_text(html,encoding='utf-8')
bundle()
